/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blockbuster;


/**
 *
 * @author kerlis
 */
public class Inicio extends javax.swing.JFrame {

   
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCatalogo = new javax.swing.JButton();
        botonAlquilar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        botonCatalogo.setBackground(new java.awt.Color(102, 102, 255));
        botonCatalogo.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        botonCatalogo.setText("Catalogo");
        botonCatalogo.setBorder(null);
        botonCatalogo.setBorderPainted(false);
        botonCatalogo.setFocusPainted(false);
        botonCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCatalogoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCatalogo);
        botonCatalogo.setBounds(260, 340, 120, 50);

        botonAlquilar.setBackground(new java.awt.Color(102, 102, 255));
        botonAlquilar.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        botonAlquilar.setText("Alquilar");
        botonAlquilar.setBorder(null);
        botonAlquilar.setBorderPainted(false);
        botonAlquilar.setFocusPainted(false);
        botonAlquilar.setFocusable(false);
        jPanel1.add(botonAlquilar);
        botonAlquilar.setBounds(80, 340, 120, 50);

        botonSalir.setBackground(new java.awt.Color(102, 102, 255));
        botonSalir.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setBorder(null);
        botonSalir.setBorderPainted(false);
        botonSalir.setFocusPainted(false);
        botonSalir.setFocusable(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir);
        botonSalir.setBounds(260, 430, 120, 50);

        botonCliente.setBackground(new java.awt.Color(102, 102, 255));
        botonCliente.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        botonCliente.setText("Clientes");
        botonCliente.setBorder(null);
        botonCliente.setBorderPainted(false);
        botonCliente.setFocusPainted(false);
        botonCliente.setFocusable(false);
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonCliente);
        botonCliente.setBounds(80, 430, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logonegro.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-120, 20, 660, 240);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cine.jpg"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(-120, -50, 990, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCatalogoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClienteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton botonAlquilar;
    private javax.swing.JButton botonCatalogo;
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
